import type { AgentPatternType, NodeConfig } from '../types';

export const nodeConfigs: Record<AgentPatternType, NodeConfig> = {
  trigger: {
    label: 'Trigger',
    description: 'Start the workflow based on an event',
    icon: 'Zap',
    color: '#22c55e',
    category: 'triggers',
    defaultData: {
      triggerType: 'manual',
      schedule: '',
      webhookPath: '',
    },
    configSchema: [
      {
        key: 'triggerType',
        label: 'Trigger Type',
        type: 'select',
        options: [
          { label: 'Manual', value: 'manual' },
          { label: 'Webhook', value: 'webhook' },
          { label: 'Schedule', value: 'schedule' },
          { label: 'Event', value: 'event' },
        ],
        defaultValue: 'manual',
      },
      {
        key: 'schedule',
        label: 'Schedule (cron)',
        type: 'text',
        placeholder: '0 9 * * 1-5',
        description: 'Cron expression for scheduled triggers',
        advanced: true,
      },
      {
        key: 'webhookPath',
        label: 'Webhook Path',
        type: 'text',
        placeholder: '/api/trigger',
        advanced: true,
      },
    ],
  },

  retrieval: {
    label: 'Retrieval & Grounding',
    description: 'Q&A from knowledge sources with context grounding',
    icon: 'Search',
    color: '#3b82f6',
    category: 'agentic',
    defaultData: {
      sources: [],
      groundingMode: 'strict',
      maxResults: 5,
      freshnessWindow: '7d',
      prompt: '',
    },
    configSchema: [
      {
        key: 'groundingMode',
        label: 'Grounding Mode',
        type: 'select',
        options: [
          { label: 'Strict - Only use retrieved context', value: 'strict' },
          { label: 'Flexible - Augment with model knowledge', value: 'flexible' },
          { label: 'Hybrid - Verify claims against sources', value: 'hybrid' },
        ],
        defaultValue: 'strict',
      },
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        defaultValue: 5,
        description: 'Maximum number of documents to retrieve',
      },
      {
        key: 'freshnessWindow',
        label: 'Freshness Window',
        type: 'select',
        options: [
          { label: 'Last 24 hours', value: '1d' },
          { label: 'Last 7 days', value: '7d' },
          { label: 'Last 30 days', value: '30d' },
          { label: 'All time', value: 'all' },
        ],
        defaultValue: '7d',
      },
      {
        key: 'prompt',
        label: 'Retrieval Prompt',
        type: 'textarea',
        placeholder: 'Enter the query or use {{input}} for dynamic input',
      },
    ],
  },

  toolUse: {
    label: 'Tool Use & Function Calling',
    description: 'Execute UiPath workflows or external APIs',
    icon: 'Wrench',
    color: '#f59e0b',
    category: 'agentic',
    defaultData: {
      tools: [],
      preconditions: '',
      retryPolicy: 'exponential',
      maxRetries: 3,
      timeout: 30000,
    },
    configSchema: [
      {
        key: 'toolSelector',
        label: 'Select Tools',
        type: 'select',
        options: [
          { label: 'HTTP Request', value: 'http' },
          { label: 'UiPath Workflow', value: 'uipath' },
          { label: 'Database Query', value: 'database' },
          { label: 'File Operations', value: 'file' },
          { label: 'Custom Function', value: 'custom' },
        ],
      },
      {
        key: 'preconditions',
        label: 'Preconditions',
        type: 'textarea',
        placeholder: 'Define conditions that must be met before tool execution',
        advanced: true,
      },
      {
        key: 'retryPolicy',
        label: 'Retry Policy',
        type: 'select',
        options: [
          { label: 'No Retry', value: 'none' },
          { label: 'Linear Backoff', value: 'linear' },
          { label: 'Exponential Backoff', value: 'exponential' },
        ],
        defaultValue: 'exponential',
      },
      {
        key: 'maxRetries',
        label: 'Max Retries',
        type: 'number',
        defaultValue: 3,
      },
    ],
  },

  planner: {
    label: 'Planner-Executor',
    description: 'Multi-step reasoning and actioning with checkpoints',
    icon: 'GitBranch',
    color: '#8b5cf6',
    category: 'agentic',
    defaultData: {
      objective: '',
      constraints: [],
      checkpoints: true,
      maxSteps: 10,
      planningModel: 'gpt-4',
    },
    configSchema: [
      {
        key: 'objective',
        label: 'Objective',
        type: 'textarea',
        placeholder: 'Describe the goal the agent should achieve',
      },
      {
        key: 'constraints',
        label: 'Constraints',
        type: 'textarea',
        placeholder: 'List constraints (one per line)',
        description: 'Boundaries the agent must operate within',
      },
      {
        key: 'checkpoints',
        label: 'Enable Checkpoints',
        type: 'boolean',
        defaultValue: true,
        description: 'Save state at each step for recovery',
      },
      {
        key: 'maxSteps',
        label: 'Max Steps',
        type: 'number',
        defaultValue: 10,
        description: 'Maximum number of planning steps',
      },
    ],
  },

  extraction: {
    label: 'Structured Extraction',
    description: 'Schema-based extraction from documents or messages',
    icon: 'FileText',
    color: '#ec4899',
    category: 'agentic',
    defaultData: {
      schema: {},
      precisionMode: 'balanced',
      validateOutput: true,
    },
    configSchema: [
      {
        key: 'schema',
        label: 'Output Schema',
        type: 'json',
        placeholder: '{\n  "name": "string",\n  "amount": "number"\n}',
        description: 'JSON schema defining the extraction structure',
      },
      {
        key: 'precisionMode',
        label: 'Precision Mode',
        type: 'select',
        options: [
          { label: 'High Recall - Extract more, verify less', value: 'recall' },
          { label: 'Balanced', value: 'balanced' },
          { label: 'High Precision - Only confident extractions', value: 'precision' },
        ],
        defaultValue: 'balanced',
      },
      {
        key: 'validateOutput',
        label: 'Validate Output',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },

  triage: {
    label: 'Document & Email Triage',
    description: 'Classification and routing based on content',
    icon: 'Mail',
    color: '#06b6d4',
    category: 'agentic',
    defaultData: {
      categories: [],
      confidenceThreshold: 0.8,
      escalationRoute: '',
    },
    configSchema: [
      {
        key: 'categories',
        label: 'Categories',
        type: 'textarea',
        placeholder: 'Enter categories (one per line)',
        description: 'Classification categories for routing',
      },
      {
        key: 'confidenceThreshold',
        label: 'Confidence Threshold',
        type: 'number',
        defaultValue: 0.8,
        description: 'Minimum confidence for auto-routing (0-1)',
      },
      {
        key: 'escalationRoute',
        label: 'Escalation Route',
        type: 'text',
        placeholder: 'Default route when confidence is low',
      },
    ],
  },

  memory: {
    label: 'Memory & Personalization',
    description: 'Stateful context and recall across sessions',
    icon: 'Brain',
    color: '#14b8a6',
    category: 'agentic',
    defaultData: {
      retentionDays: 30,
      autoWriteTriggers: [],
      memoryScope: 'user',
    },
    configSchema: [
      {
        key: 'memoryScope',
        label: 'Memory Scope',
        type: 'select',
        options: [
          { label: 'User - Personal memory', value: 'user' },
          { label: 'Session - Current session only', value: 'session' },
          { label: 'Global - Shared across all users', value: 'global' },
        ],
        defaultValue: 'user',
      },
      {
        key: 'retentionDays',
        label: 'Retention (days)',
        type: 'number',
        defaultValue: 30,
        description: 'How long to retain memories',
      },
      {
        key: 'autoWriteTriggers',
        label: 'Auto-Write Triggers',
        type: 'textarea',
        placeholder: 'Conditions that trigger memory writes',
        advanced: true,
      },
    ],
  },

  evaluation: {
    label: 'Evaluation & Experiments',
    description: 'Testing and benchmarking agent performance',
    icon: 'FlaskConical',
    color: '#f97316',
    category: 'control',
    defaultData: {
      dataset: '',
      metrics: ['accuracy', 'latency'],
      threshold: 0.9,
    },
    configSchema: [
      {
        key: 'dataset',
        label: 'Evaluation Dataset',
        type: 'text',
        placeholder: 'Path or ID of the evaluation dataset',
      },
      {
        key: 'metrics',
        label: 'Metrics',
        type: 'select',
        options: [
          { label: 'Accuracy', value: 'accuracy' },
          { label: 'Latency', value: 'latency' },
          { label: 'Token Usage', value: 'tokens' },
          { label: 'Cost', value: 'cost' },
        ],
      },
      {
        key: 'threshold',
        label: 'Success Threshold',
        type: 'number',
        defaultValue: 0.9,
      },
    ],
  },

  humanInLoop: {
    label: 'Human-in-the-Loop',
    description: 'Manual approval checkpoints with SLA tracking',
    icon: 'UserCheck',
    color: '#ef4444',
    category: 'control',
    defaultData: {
      approvalType: 'single',
      roles: [],
      slaMinutes: 60,
      escalationPath: '',
    },
    configSchema: [
      {
        key: 'approvalType',
        label: 'Approval Type',
        type: 'select',
        options: [
          { label: 'Single Approver', value: 'single' },
          { label: 'Multiple Approvers (Any)', value: 'any' },
          { label: 'Multiple Approvers (All)', value: 'all' },
          { label: 'Sequential', value: 'sequential' },
        ],
        defaultValue: 'single',
      },
      {
        key: 'roles',
        label: 'Authorized Roles',
        type: 'textarea',
        placeholder: 'Enter roles (one per line)',
      },
      {
        key: 'slaMinutes',
        label: 'SLA (minutes)',
        type: 'number',
        defaultValue: 60,
        description: 'Time limit for approval before escalation',
      },
      {
        key: 'escalationPath',
        label: 'Escalation Path',
        type: 'text',
        placeholder: 'Who to notify if SLA is breached',
      },
    ],
  },

  llm: {
    label: 'LLM / AI Model',
    description: 'Call a language model for reasoning or generation',
    icon: 'Sparkles',
    color: '#a855f7',
    category: 'agentic',
    defaultData: {
      model: 'gpt-4',
      prompt: '',
      temperature: 0.7,
      maxTokens: 1000,
      systemPrompt: '',
    },
    configSchema: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        options: [
          { label: 'GPT-4', value: 'gpt-4' },
          { label: 'GPT-4 Turbo', value: 'gpt-4-turbo' },
          { label: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' },
          { label: 'Claude 3 Opus', value: 'claude-3-opus' },
          { label: 'Claude 3 Sonnet', value: 'claude-3-sonnet' },
        ],
        defaultValue: 'gpt-4',
      },
      {
        key: 'systemPrompt',
        label: 'System Prompt',
        type: 'textarea',
        placeholder: 'Define the AI assistant behavior',
      },
      {
        key: 'prompt',
        label: 'User Prompt',
        type: 'textarea',
        placeholder: 'The prompt to send to the model. Use {{variable}} for inputs.',
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'number',
        defaultValue: 0.7,
        description: 'Creativity (0 = deterministic, 1 = creative)',
      },
      {
        key: 'maxTokens',
        label: 'Max Tokens',
        type: 'number',
        defaultValue: 1000,
        advanced: true,
      },
    ],
  },

  output: {
    label: 'Output',
    description: 'Return the final result of the workflow',
    icon: 'ArrowRightCircle',
    color: '#64748b',
    category: 'actions',
    defaultData: {
      outputFormat: 'json',
      schema: {},
    },
    configSchema: [
      {
        key: 'outputFormat',
        label: 'Output Format',
        type: 'select',
        options: [
          { label: 'JSON', value: 'json' },
          { label: 'Text', value: 'text' },
          { label: 'Structured', value: 'structured' },
        ],
        defaultValue: 'json',
      },
      {
        key: 'schema',
        label: 'Output Schema',
        type: 'json',
        placeholder: '{}',
        advanced: true,
      },
    ],
  },

  // ============================================
  // Generic Agent Node
  // ============================================
  agent: {
    label: 'Agent',
    description: 'Autonomous agent with tools, memory, and reasoning',
    icon: 'Bot',
    color: '#6366f1',
    category: 'agentic',
    defaultData: {
      name: 'Agent',
      role: '',
      goal: '',
      model: 'gpt-4',
      temperature: 0.7,
      tools: [],
      memoryType: 'conversation',
      reasoningMode: 'react',
      maxIterations: 10,
      confidenceThreshold: 0.8,
      hitlMode: 'on_low_confidence',
    },
    configSchema: [
      {
        key: 'name',
        label: 'Agent Name',
        type: 'text',
        placeholder: 'My Agent',
        description: 'A unique name for this agent',
      },
      {
        key: 'role',
        label: 'Role',
        type: 'text',
        placeholder: 'Research Assistant',
        description: 'The role this agent plays in the workflow',
      },
      {
        key: 'goal',
        label: 'Goal',
        type: 'textarea',
        placeholder: 'Describe what this agent should accomplish',
        description: 'The primary objective for this agent',
      },
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        options: [
          { label: 'GPT-4', value: 'gpt-4' },
          { label: 'GPT-4 Turbo', value: 'gpt-4-turbo' },
          { label: 'Claude 3 Opus', value: 'claude-3-opus' },
          { label: 'Claude 3 Sonnet', value: 'claude-3-sonnet' },
          { label: 'Claude 3 Haiku', value: 'claude-3-haiku' },
        ],
        defaultValue: 'gpt-4',
      },
      {
        key: 'temperature',
        label: 'Temperature',
        type: 'number',
        defaultValue: 0.7,
        description: 'Creativity level (0 = deterministic, 1 = creative)',
      },
      {
        key: 'memoryType',
        label: 'Memory Type',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Conversation', value: 'conversation' },
          { label: 'Episodic', value: 'episodic' },
          { label: 'Semantic', value: 'semantic' },
        ],
        defaultValue: 'conversation',
      },
      {
        key: 'reasoningMode',
        label: 'Reasoning Mode',
        type: 'select',
        options: [
          { label: 'ReAct (Reasoning + Acting)', value: 'react' },
          { label: 'Chain of Thought', value: 'cot' },
          { label: 'Reflexion (Self-correction)', value: 'reflexion' },
        ],
        defaultValue: 'react',
        description: 'How the agent reasons through tasks',
      },
      {
        key: 'maxIterations',
        label: 'Max Iterations',
        type: 'number',
        defaultValue: 10,
        description: 'Maximum reasoning/action cycles',
        advanced: true,
      },
      {
        key: 'confidenceThreshold',
        label: 'Confidence Threshold',
        type: 'number',
        defaultValue: 0.8,
        description: 'Minimum confidence for auto-actions (0-1)',
        advanced: true,
      },
      {
        key: 'hitlMode',
        label: 'Human-in-the-Loop',
        type: 'select',
        options: [
          { label: 'Never', value: 'never' },
          { label: 'On Low Confidence', value: 'on_low_confidence' },
          { label: 'On Destructive Actions', value: 'on_destructive' },
          { label: 'Always', value: 'always' },
        ],
        defaultValue: 'on_low_confidence',
        advanced: true,
      },
    ],
  },

  // ============================================
  // Specialized Pattern Nodes
  // ============================================
  deepRAG: {
    label: 'Deep RAG',
    description: 'Research queries with citations, grounding sources, and evidence tracking',
    icon: 'BookOpen',
    color: '#0ea5e9',
    category: 'patterns',
    isPattern: true,
    patternCategory: 'research',
    hasSpecializedEditor: true,
    defaultData: {
      queryType: 'single',
      queries: [],
      groundingSources: [],
      scopeFilters: [],
      citationMode: 'strict',
      evidenceThreshold: 0.7,
      maxSources: 10,
      synthesisInstructions: '',
      followUpEnabled: true,
    },
    configSchema: [
      {
        key: 'queryType',
        label: 'Query Type',
        type: 'select',
        options: [
          { label: 'Single Query', value: 'single' },
          { label: 'Multi-Query', value: 'multi' },
        ],
        defaultValue: 'single',
      },
      {
        key: 'queries',
        label: 'Research Queries',
        type: 'textarea',
        placeholder: 'Enter queries (one per line)',
        description: 'Questions to research against grounding sources',
      },
      {
        key: 'citationMode',
        label: 'Citation Mode',
        type: 'select',
        options: [
          { label: 'Strict - All claims must have citations', value: 'strict' },
          { label: 'Relaxed - Best effort citations', value: 'relaxed' },
        ],
        defaultValue: 'strict',
      },
      {
        key: 'evidenceThreshold',
        label: 'Evidence Threshold',
        type: 'number',
        defaultValue: 0.7,
        description: 'Minimum relevance score for evidence (0-1)',
      },
      {
        key: 'maxSources',
        label: 'Max Sources',
        type: 'number',
        defaultValue: 10,
        description: 'Maximum number of sources to include',
      },
      {
        key: 'synthesisInstructions',
        label: 'Synthesis Instructions',
        type: 'textarea',
        placeholder: 'How to synthesize and present the research findings',
        advanced: true,
      },
      {
        key: 'followUpEnabled',
        label: 'Enable Follow-up Questions',
        type: 'boolean',
        defaultValue: true,
        description: 'Allow generating follow-up research questions',
      },
    ],
  },

  batchTransform: {
    label: 'Batch Transform',
    description: 'Tabular data transformation with schema mapping and validation',
    icon: 'Table',
    color: '#10b981',
    category: 'patterns',
    isPattern: true,
    patternCategory: 'transformation',
    hasSpecializedEditor: true,
    defaultData: {
      inputType: 'csv',
      inputSchema: [],
      outputSchema: [],
      batchSize: 100,
      parallelism: 4,
      groundingMode: 'none',
      validationRules: [],
      confidenceThreshold: 0.85,
      routingRules: [],
    },
    configSchema: [
      {
        key: 'inputType',
        label: 'Input Type',
        type: 'select',
        options: [
          { label: 'CSV', value: 'csv' },
          { label: 'JSON', value: 'json' },
          { label: 'API', value: 'api' },
        ],
        defaultValue: 'csv',
      },
      {
        key: 'batchSize',
        label: 'Batch Size',
        type: 'number',
        defaultValue: 100,
        description: 'Number of rows to process per batch',
      },
      {
        key: 'parallelism',
        label: 'Parallelism',
        type: 'number',
        defaultValue: 4,
        description: 'Number of parallel processing threads',
      },
      {
        key: 'groundingMode',
        label: 'Grounding Mode',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Web Search', value: 'web' },
          { label: 'Knowledge Index', value: 'index' },
        ],
        defaultValue: 'none',
        description: 'External data source for enrichment',
      },
      {
        key: 'confidenceThreshold',
        label: 'Confidence Threshold',
        type: 'number',
        defaultValue: 0.85,
        description: 'Minimum confidence for auto-approval',
      },
    ],
  },

  textSummarization: {
    label: 'Text Summarization',
    description: 'Summarize documents with configurable length and style',
    icon: 'FileText',
    color: '#f59e0b',
    category: 'patterns',
    isPattern: true,
    patternCategory: 'summarization',
    defaultData: {
      summaryLength: 'medium',
      style: 'professional',
      preserveKeyPoints: true,
      includeMetadata: false,
    },
    configSchema: [
      {
        key: 'summaryLength',
        label: 'Summary Length',
        type: 'select',
        options: [
          { label: 'Brief (1-2 sentences)', value: 'brief' },
          { label: 'Medium (1 paragraph)', value: 'medium' },
          { label: 'Detailed (multiple paragraphs)', value: 'detailed' },
        ],
        defaultValue: 'medium',
      },
      {
        key: 'style',
        label: 'Writing Style',
        type: 'select',
        options: [
          { label: 'Professional', value: 'professional' },
          { label: 'Casual', value: 'casual' },
          { label: 'Technical', value: 'technical' },
          { label: 'Executive Summary', value: 'executive' },
        ],
        defaultValue: 'professional',
      },
      {
        key: 'preserveKeyPoints',
        label: 'Preserve Key Points',
        type: 'boolean',
        defaultValue: true,
        description: 'Ensure critical information is retained',
      },
      {
        key: 'includeMetadata',
        label: 'Include Metadata',
        type: 'boolean',
        defaultValue: false,
        description: 'Add source info and confidence scores',
        advanced: true,
      },
    ],
  },

  tabularReasoning: {
    label: 'Tabular Reasoning',
    description: 'Analyze and reason over structured tabular data',
    icon: 'Grid3x3',
    color: '#8b5cf6',
    category: 'patterns',
    isPattern: true,
    patternCategory: 'transformation',
    defaultData: {
      analysisType: 'aggregate',
      groupBy: [],
      calculations: [],
      naturalLanguageQuery: '',
    },
    configSchema: [
      {
        key: 'analysisType',
        label: 'Analysis Type',
        type: 'select',
        options: [
          { label: 'Aggregation', value: 'aggregate' },
          { label: 'Comparison', value: 'comparison' },
          { label: 'Trend Analysis', value: 'trend' },
          { label: 'Anomaly Detection', value: 'anomaly' },
        ],
        defaultValue: 'aggregate',
      },
      {
        key: 'naturalLanguageQuery',
        label: 'Natural Language Query',
        type: 'textarea',
        placeholder: 'Ask a question about the data',
        description: 'Query the data using natural language',
      },
    ],
  },

  documentProcessing: {
    label: 'Document Processing',
    description: 'Extract, classify, and process documents at scale',
    icon: 'Files',
    color: '#ec4899',
    category: 'patterns',
    isPattern: true,
    patternCategory: 'research',
    defaultData: {
      processingMode: 'extract',
      documentTypes: [],
      extractionSchema: {},
      ocrEnabled: true,
    },
    configSchema: [
      {
        key: 'processingMode',
        label: 'Processing Mode',
        type: 'select',
        options: [
          { label: 'Extract Data', value: 'extract' },
          { label: 'Classify', value: 'classify' },
          { label: 'Summarize', value: 'summarize' },
          { label: 'Compare', value: 'compare' },
        ],
        defaultValue: 'extract',
      },
      {
        key: 'documentTypes',
        label: 'Document Types',
        type: 'textarea',
        placeholder: 'PDF, DOCX, images, etc.',
        description: 'Supported document formats',
      },
      {
        key: 'ocrEnabled',
        label: 'Enable OCR',
        type: 'boolean',
        defaultValue: true,
        description: 'Extract text from images and scanned documents',
      },
      {
        key: 'extractionSchema',
        label: 'Extraction Schema',
        type: 'json',
        placeholder: '{}',
        description: 'JSON schema for structured extraction',
        advanced: true,
      },
    ],
  },

  // ============================================
  // Context Engineering Nodes
  // ============================================
  contextWrite: {
    label: 'Write Context',
    description: 'Save information to scratchpad or memory stores',
    icon: 'PenLine',
    color: '#22d3ee',
    category: 'context',
    defaultData: {
      targetStore: 'scratchpad',
      key: '',
      ttl: null,
      overwritePolicy: 'always',
    },
    configSchema: [
      {
        key: 'targetStore',
        label: 'Target Store',
        type: 'select',
        options: [
          { label: 'Scratchpad (temporary)', value: 'scratchpad' },
          { label: 'Episodic Memory', value: 'episodic' },
          { label: 'Procedural Memory', value: 'procedural' },
          { label: 'Semantic Memory', value: 'semantic' },
        ],
        defaultValue: 'scratchpad',
      },
      {
        key: 'key',
        label: 'Storage Key',
        type: 'text',
        placeholder: 'my_data_key',
        description: 'Identifier for retrieving this data later',
      },
      {
        key: 'ttl',
        label: 'TTL (seconds)',
        type: 'number',
        placeholder: 'Leave empty for no expiration',
        description: 'Time-to-live before auto-deletion',
        advanced: true,
      },
      {
        key: 'overwritePolicy',
        label: 'Overwrite Policy',
        type: 'select',
        options: [
          { label: 'Always Overwrite', value: 'always' },
          { label: 'Only if Empty', value: 'if_empty' },
          { label: 'Append', value: 'append' },
        ],
        defaultValue: 'always',
      },
    ],
  },

  contextSelect: {
    label: 'Select Context',
    description: 'Retrieve relevant information from various sources',
    icon: 'MousePointer2',
    color: '#a78bfa',
    category: 'context',
    defaultData: {
      sourceType: 'memory',
      query: '',
      maxResults: 5,
      relevanceThreshold: 0.7,
      includeMetadata: true,
    },
    configSchema: [
      {
        key: 'sourceType',
        label: 'Source Type',
        type: 'select',
        options: [
          { label: 'RAG / Knowledge Base', value: 'rag' },
          { label: 'Memory Store', value: 'memory' },
          { label: 'Rules File', value: 'rules_file' },
          { label: 'Tool Results', value: 'tool_results' },
        ],
        defaultValue: 'memory',
      },
      {
        key: 'query',
        label: 'Selection Query',
        type: 'textarea',
        placeholder: 'Query to find relevant context',
        description: 'Natural language or key-based query',
      },
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        defaultValue: 5,
        description: 'Maximum items to retrieve',
      },
      {
        key: 'relevanceThreshold',
        label: 'Relevance Threshold',
        type: 'number',
        defaultValue: 0.7,
        description: 'Minimum relevance score (0-1)',
      },
      {
        key: 'includeMetadata',
        label: 'Include Metadata',
        type: 'boolean',
        defaultValue: true,
        description: 'Return source and scoring info',
      },
    ],
  },

  contextCompress: {
    label: 'Compress Context',
    description: 'Reduce context size while preserving key information',
    icon: 'Minimize2',
    color: '#fb923c',
    category: 'context',
    defaultData: {
      strategy: 'summarize',
      targetTokens: 2000,
      preservePriority: [],
      triggerThreshold: 0.8,
    },
    configSchema: [
      {
        key: 'strategy',
        label: 'Compression Strategy',
        type: 'select',
        options: [
          { label: 'Summarize', value: 'summarize' },
          { label: 'Trim Oldest', value: 'trim' },
          { label: 'Selective (Keep Priority)', value: 'selective' },
        ],
        defaultValue: 'summarize',
      },
      {
        key: 'targetTokens',
        label: 'Target Tokens',
        type: 'number',
        defaultValue: 2000,
        description: 'Desired context size after compression',
      },
      {
        key: 'preservePriority',
        label: 'Preserve Keys',
        type: 'textarea',
        placeholder: 'Keys or sections to preserve (one per line)',
        description: 'High-priority content to keep',
        advanced: true,
      },
      {
        key: 'triggerThreshold',
        label: 'Trigger Threshold',
        type: 'number',
        defaultValue: 0.8,
        description: 'Compress when context exceeds this % of window',
        advanced: true,
      },
    ],
  },

  contextIsolate: {
    label: 'Isolate Context',
    description: 'Split context across agents with controlled sharing',
    icon: 'Split',
    color: '#f472b6',
    category: 'context',
    defaultData: {
      isolationMode: 'full',
      sharedKeys: [],
      propagateResults: true,
    },
    configSchema: [
      {
        key: 'isolationMode',
        label: 'Isolation Mode',
        type: 'select',
        options: [
          { label: 'Full Isolation', value: 'full' },
          { label: 'Shared Read', value: 'shared_read' },
          { label: 'Shared Write', value: 'shared_write' },
        ],
        defaultValue: 'full',
        description: 'How much context to share between agents',
      },
      {
        key: 'sharedKeys',
        label: 'Shared Keys',
        type: 'textarea',
        placeholder: 'Keys to share (one per line)',
        description: 'Specific context keys to share',
      },
      {
        key: 'propagateResults',
        label: 'Propagate Results',
        type: 'boolean',
        defaultValue: true,
        description: 'Pass results back to parent context',
      },
    ],
  },

  // ============================================
  // Data Pipeline Nodes
  // ============================================
  dataIngestion: {
    label: 'Data Ingestion',
    description: 'Import data from various sources and formats',
    icon: 'Download',
    color: '#34d399',
    category: 'dataPipeline',
    defaultData: {
      sourceType: 'api',
      connectionString: '',
      schedule: '',
      validation: true,
    },
    configSchema: [
      {
        key: 'sourceType',
        label: 'Source Type',
        type: 'select',
        options: [
          { label: 'API Endpoint', value: 'api' },
          { label: 'Database', value: 'database' },
          { label: 'File Upload', value: 'file' },
          { label: 'Webhook', value: 'webhook' },
          { label: 'Message Queue', value: 'queue' },
        ],
        defaultValue: 'api',
      },
      {
        key: 'connectionString',
        label: 'Connection String',
        type: 'text',
        placeholder: 'Connection details or URL',
      },
      {
        key: 'schedule',
        label: 'Ingestion Schedule',
        type: 'text',
        placeholder: 'Cron expression (e.g., 0 */6 * * *)',
        advanced: true,
      },
      {
        key: 'validation',
        label: 'Validate on Ingestion',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },

  dataAggregation: {
    label: 'Data Aggregation',
    description: 'Combine and aggregate data from multiple sources',
    icon: 'Layers',
    color: '#60a5fa',
    category: 'dataPipeline',
    defaultData: {
      aggregationType: 'merge',
      joinKey: '',
      deduplication: true,
    },
    configSchema: [
      {
        key: 'aggregationType',
        label: 'Aggregation Type',
        type: 'select',
        options: [
          { label: 'Merge', value: 'merge' },
          { label: 'Union', value: 'union' },
          { label: 'Join', value: 'join' },
          { label: 'Concatenate', value: 'concat' },
        ],
        defaultValue: 'merge',
      },
      {
        key: 'joinKey',
        label: 'Join Key',
        type: 'text',
        placeholder: 'Field to join on',
        description: 'Required for join operations',
      },
      {
        key: 'deduplication',
        label: 'Remove Duplicates',
        type: 'boolean',
        defaultValue: true,
      },
    ],
  },

  rulesRouting: {
    label: 'Rules & Routing',
    description: 'Route data based on configurable rules and conditions',
    icon: 'GitBranch',
    color: '#c084fc',
    category: 'dataPipeline',
    defaultData: {
      rules: [],
      defaultRoute: 'passthrough',
      evaluationMode: 'first_match',
    },
    configSchema: [
      {
        key: 'rules',
        label: 'Routing Rules',
        type: 'json',
        placeholder: '[{"condition": "...", "route": "..."}]',
        description: 'Define routing logic as JSON rules',
      },
      {
        key: 'defaultRoute',
        label: 'Default Route',
        type: 'text',
        placeholder: 'Route when no rules match',
        defaultValue: 'passthrough',
      },
      {
        key: 'evaluationMode',
        label: 'Evaluation Mode',
        type: 'select',
        options: [
          { label: 'First Match', value: 'first_match' },
          { label: 'All Matches', value: 'all_matches' },
          { label: 'Best Match', value: 'best_match' },
        ],
        defaultValue: 'first_match',
      },
    ],
  },

  synthesis: {
    label: 'Synthesis',
    description: 'Combine insights and generate synthesized outputs',
    icon: 'Sparkles',
    color: '#fbbf24',
    category: 'dataPipeline',
    defaultData: {
      synthesisMode: 'narrative',
      template: '',
      includeEvidence: true,
    },
    configSchema: [
      {
        key: 'synthesisMode',
        label: 'Synthesis Mode',
        type: 'select',
        options: [
          { label: 'Narrative Summary', value: 'narrative' },
          { label: 'Structured Report', value: 'report' },
          { label: 'Key Insights', value: 'insights' },
          { label: 'Comparison Matrix', value: 'comparison' },
        ],
        defaultValue: 'narrative',
      },
      {
        key: 'template',
        label: 'Output Template',
        type: 'textarea',
        placeholder: 'Custom template for synthesis output',
        advanced: true,
      },
      {
        key: 'includeEvidence',
        label: 'Include Evidence',
        type: 'boolean',
        defaultValue: true,
        description: 'Cite sources in synthesis',
      },
    ],
  },

  contentCreation: {
    label: 'Content Creation',
    description: 'Generate content based on data and templates',
    icon: 'FileEdit',
    color: '#f87171',
    category: 'dataPipeline',
    defaultData: {
      contentType: 'document',
      tone: 'professional',
      length: 'medium',
      format: 'markdown',
    },
    configSchema: [
      {
        key: 'contentType',
        label: 'Content Type',
        type: 'select',
        options: [
          { label: 'Document', value: 'document' },
          { label: 'Email', value: 'email' },
          { label: 'Report', value: 'report' },
          { label: 'Presentation', value: 'presentation' },
        ],
        defaultValue: 'document',
      },
      {
        key: 'tone',
        label: 'Tone',
        type: 'select',
        options: [
          { label: 'Professional', value: 'professional' },
          { label: 'Casual', value: 'casual' },
          { label: 'Formal', value: 'formal' },
          { label: 'Technical', value: 'technical' },
        ],
        defaultValue: 'professional',
      },
      {
        key: 'length',
        label: 'Length',
        type: 'select',
        options: [
          { label: 'Brief', value: 'brief' },
          { label: 'Medium', value: 'medium' },
          { label: 'Detailed', value: 'detailed' },
        ],
        defaultValue: 'medium',
      },
      {
        key: 'format',
        label: 'Output Format',
        type: 'select',
        options: [
          { label: 'Markdown', value: 'markdown' },
          { label: 'HTML', value: 'html' },
          { label: 'Plain Text', value: 'text' },
        ],
        defaultValue: 'markdown',
      },
    ],
  },

  diagnosis: {
    label: 'Diagnosis',
    description: 'Analyze data and identify issues or patterns',
    icon: 'Stethoscope',
    color: '#4ade80',
    category: 'dataPipeline',
    defaultData: {
      analysisType: 'anomaly',
      threshold: 0.9,
      generateRecommendations: true,
    },
    configSchema: [
      {
        key: 'analysisType',
        label: 'Analysis Type',
        type: 'select',
        options: [
          { label: 'Anomaly Detection', value: 'anomaly' },
          { label: 'Root Cause Analysis', value: 'root_cause' },
          { label: 'Pattern Recognition', value: 'pattern' },
          { label: 'Health Check', value: 'health' },
        ],
        defaultValue: 'anomaly',
      },
      {
        key: 'threshold',
        label: 'Detection Threshold',
        type: 'number',
        defaultValue: 0.9,
        description: 'Sensitivity for issue detection',
      },
      {
        key: 'generateRecommendations',
        label: 'Generate Recommendations',
        type: 'boolean',
        defaultValue: true,
        description: 'Include suggested actions',
      },
    ],
  },

  feedback: {
    label: 'Feedback Loop',
    description: 'Collect feedback and improve pipeline performance',
    icon: 'MessageCircle',
    color: '#818cf8',
    category: 'dataPipeline',
    defaultData: {
      feedbackType: 'explicit',
      collectMetrics: true,
      autoAdjust: false,
    },
    configSchema: [
      {
        key: 'feedbackType',
        label: 'Feedback Type',
        type: 'select',
        options: [
          { label: 'Explicit (User ratings)', value: 'explicit' },
          { label: 'Implicit (Usage patterns)', value: 'implicit' },
          { label: 'Automated (Quality metrics)', value: 'automated' },
        ],
        defaultValue: 'explicit',
      },
      {
        key: 'collectMetrics',
        label: 'Collect Metrics',
        type: 'boolean',
        defaultValue: true,
        description: 'Track performance metrics',
      },
      {
        key: 'autoAdjust',
        label: 'Auto-Adjust',
        type: 'boolean',
        defaultValue: false,
        description: 'Automatically tune parameters based on feedback',
        advanced: true,
      },
    ],
  },
};

export const getNodeConfig = (type: AgentPatternType): NodeConfig => {
  return nodeConfigs[type];
};

export const nodeCategories = {
  triggers: {
    label: 'Triggers',
    description: 'Start your workflow',
    types: ['trigger'] as AgentPatternType[],
  },
  agentic: {
    label: 'Agentic Patterns',
    description: 'AI-powered automation blocks',
    types: ['agent', 'retrieval', 'toolUse', 'planner', 'extraction', 'triage', 'memory', 'llm'] as AgentPatternType[],
  },
  patterns: {
    label: 'Specialized Patterns',
    description: 'Pre-built pattern templates with custom UIs',
    types: ['deepRAG', 'batchTransform', 'textSummarization', 'tabularReasoning', 'documentProcessing'] as AgentPatternType[],
  },
  context: {
    label: 'Context Engineering',
    description: 'Manage context across agents',
    types: ['contextWrite', 'contextSelect', 'contextCompress', 'contextIsolate'] as AgentPatternType[],
  },
  dataPipeline: {
    label: 'Data Pipeline',
    description: 'Data transformation and processing stages',
    types: ['dataIngestion', 'dataAggregation', 'rulesRouting', 'synthesis', 'contentCreation', 'diagnosis', 'feedback'] as AgentPatternType[],
  },
  control: {
    label: 'Control Flow',
    description: 'Manage workflow execution',
    types: ['humanInLoop', 'evaluation'] as AgentPatternType[],
  },
  actions: {
    label: 'Actions',
    description: 'Output and side effects',
    types: ['output'] as AgentPatternType[],
  },
};
